### ISSUE TITLE
IncorrectContextUseViolation in strict mode

### ISSUE THREAD

**Issue by JoshuaBradbury** [AppsFlyerSDK/appsflyer-android-sdk#17]
When retrieving the display information the SDK gets the window service and gets the metrics for the default display. This causes an IncorrectContextUseViolation due to acessing a visual service WindowManager from a non-visual Context. I believe this warning is new with Android 11.

The fix should be as simple as getting the display metrics from the resources directly, rather than through the window manager.

**Comment by riggaroo** [comment]
We are also getting a ton of these logs. 
```
Tried to access visual service WindowManager from a non-visual Context:@7cfa33c Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.DebugApplication@7cfa33c
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1914)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
        at com.appsflyer.AppsFlyerLibCore.ı(:2198)
        at com.appsflyer.AppsFlyerLibCore.ǃ(:1834)
        at com.appsflyer.AppsFlyerLibCore.ι(:1626)
        at com.appsflyer.AppsFlyerLibCore.ι(:105)
        at com.appsflyer.AppsFlyerLibCore$e.run(:3377)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.appsflyer.AFExecutor$1$1.run(:31)
        at java.lang.Thread.run(Thread.java:923)
2021-03-05 17:21:05.159 29658-4438/app.over.editor.debug D/StrictMode: Strict
```

**Comment by af-vs** [comment]
Thanks for reporting this! We will check this matter and update on our findings

**Comment by kaeawc** [comment]
Also seeing this in our logs, its one of the few StrictMode violations we have left:

```
Tried to access visual service WindowManager from a non-visual Context:co.hinge.app.App@ce7dbd1 Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:co.hinge.app.App@ce7dbd1
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1914)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
        at com.appsflyer.AppsFlyerLibCore.AFDateFormat(:2054)
        at com.appsflyer.AppsFlyerLibCore.valueOf(:1673)
        at com.appsflyer.AppsFlyerLibCore.AFDateFormat(:50691)
        at com.appsflyer.AppsFlyerLibCore$c.run(:3170)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.appsflyer.AFExecutor$1$4.run(:31)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by matsujun** [comment]
This is very similar issue.
https://github.com/microsoft/appcenter-sdk-android/issues/1427

They changed to use `DisplayManager` instead of `WindowManager` to get defaultDisplay.

**Comment by csi111** [comment]
This issue continues to occur in the following versions of the Appslfyer Android SDK.

{ group = "com.appsflyer", name = "af-android-sdk", version = "6.12.1" }

```
StrictMode policy violation: android.os.strictmode.IncorrectContextUseViolation: WindowManager should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
                                                                                                    	at android.os.StrictMode.onIncorrectContextUsed(StrictMode.java:2260)
                                                                                                    	at android.app.ContextImpl.getSystemService(ContextImpl.java:2196)
                                                                                                    	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:917)
                                                                                                    	at com.appsflyer.internal.AFe1uSDK.AFKeystoreWrapper(:1109)
                                                                                                    	at com.appsflyer.internal.AFa1dSDK.values(:1626)
                                                                                                    	at com.appsflyer.internal.AFa1dSDK.valueOf(:1451)
                                                                                                    	at com.appsflyer.internal.AFa1dSDK.values(:118)
                                                                                                    	at com.appsflyer.internal.AFa1dSDK$AFa1vSDK.run(:2477)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.IllegalAccessException: Tried to 
```
