### ISSUE TITLE
No static method values(D)D in class Lcom/appsflyer/internal/l; or its super classes (declaration of 'com.appsflyer.internal.l' appears in base.apk

### ISSUE THREAD

**Issue by Jake-Jiang** [AppsFlyerSDK/appsflyer-android-sdk#35]
2022-04-14 09:10:13.416 14499-14807/? E/AppsFlyer_6.5.0: No static method values(D)D in class Lcom/appsflyer/internal/l; or its super classes (declaration of 'com.appsflyer.internal.l' appears in base.apk)
    java.lang.NoSuchMethodError: No static method values(D)D in class Lcom/appsflyer/internal/l; or its super classes (declaration of 'com.appsflyer.internal.l' appears in /data/app/base.apk)
        at com.appsflyer.internal.t.AFInAppEventParameterName(:217)
        at com.appsflyer.internal.p.AFInAppEventParameterName(:206)
        at com.appsflyer.internal.t.AFKeystoreWrapper(:846)
        at com.appsflyer.internal.p.AFInAppEventParameterName(:194)
        at com.appsflyer.internal.r.valueOf(:618)
        at com.appsflyer.internal.p.AFInAppEventParameterName(:190)
        at com.appsflyer.internal.t.AFKeystoreWrapper(:846)
        at com.appsflyer.internal.p.AFInAppEventParameterName(:194)
        at com.appsflyer.internal.t.AFKeystoreWrapper(:846)
        at com.appsflyer.internal.t.toString(:815)
        at com.appsflyer.internal.o.AFKeystoreWrapper(:32)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.appsflyer.internal.ah$b.run(:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.appsflyer.internal.k$4$4.run(:2)
        at java.lang.Thread.run(Thread.java:920)

**Comment by pazlavi** [comment]
Hi @Jake-Jiangת
Thank you for reaching out to us.

Please make sure that you added the following keep rule: 
```
-keep class com.appsflyer.** { *; }
```

Also, make sure that your generated SDK is not missing our [resources files](https://dev.appsflyer.com/hc/docs/install-android-sdk#missing-resource-files).
If the issue persists, we would kindly ask you to submit a support ticket to support@appsflyer.com to provide optimal support. 

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by Jake-Jiang** [comment]
Hi @pazlavi ，Thanks for the quick reply, I confirm it has been added the following keep rule:

-keep class com.appsflyer.** { *; }

Also, I make sure that the generated SDK is not missing our resources files.

I found the reason may be upgrade the Braintree SDK, if I don't upgrade Braintree SDK, AppsFlyer works normally, I am more puzzled why upgrading the Braintree SDK will affect AppsFlyer

**Comment by rodrigoarias** [comment]
Having the same issue here. This is the log:

```
No static method AFInAppEventParameterName(Ljava/lang/String;)Lcom/appsflyer/internal/f; in class Lcom/appsflyer/internal/f; or its super classes (declaration of 'com.appsflyer.internal.f' appears in /data/app/~~zdDESQtK2AfhOCiar0RvUQ==/ar.com.bancar.uala-j25o9pA8_Zj7KtiAXBS2QA==/base.apk!classes3.dex)
                                                                                                    java.lang.NoSuchMethodError: No static method AFInAppEventParameterName(Ljava/lang/String;)Lcom/appsflyer/internal/f; in class Lcom/appsflyer/internal/f; or its super classes (declaration of 'com.appsflyer.internal.f' appears in /data/app/~~zdDESQtK2AfhOCiar0RvUQ==/ar.com.bancar.uala-j25o9pA8_Zj7KtiAXBS2QA==/base.apk!classes3.dex)
                                                                                                    	at com.appsflyer.internal.o.values(:36)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.appsflyer.internal.ae$d.run(:298)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.appsflyer.internal.k$1$5.run(:12)
```

I also have the following line in the rules:
`-keep class com.appsflyer.** { *; }`

And I do not have the Braintree SDK.
The AppsFlyer SDK version I'm using is 6.3.2

**Comment by pazlavi** [comment]
@rodrigoarias , 
Please update to the latest SDK version

**Comment by rodrigoarias** [comment]
Thanks @pazlavi, version 6.9.2 seems to fix the problem.
