### ISSUE TITLE
AFKeystoreWrapper throws exception

### ISSUE THREAD

**Issue by lamhoangx** [AppsFlyerSDK/appsflyer-android-sdk#51]
After using `AppsFlyerLib.getInstance().performOnDeepLinking` on app resume, we met the issues.
Version: 6.9.4
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=8; index=9
       at android.util.ArrayMap.freeArrays(ArrayMap.java:224)
       at android.util.ArrayMap.put(ArrayMap.java:471)
       at android.os.BaseBundle.putLong(BaseBundle.java:467)
       at android.content.Intent.putExtra(Intent.java:7738)
       at com.appsflyer.internal.AFa1sSDK.AFKeystoreWrapper(SourceFile)
       at com.appsflyer.internal.AFa1sSDK.AFInAppEventType(SourceFile)
       at com.appsflyer.internal.AFb1zSDK.AFInAppEventType(AFb1zSDK.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```
       
```
Fatal Exception: java.util.ConcurrentModificationException:
     at android.util.ArrayMap.put(ArrayMap.java:538)
     at android.os.BaseBundle.putLong(BaseBundle.java:597)
     at android.content.Intent.putExtra(Intent.java:8284)
     at com.appsflyer.internal.AFa1sSDK.AFKeystoreWrapper(:169)
     at com.appsflyer.internal.AFa1sSDK.AFInAppEventType(:19)
     at com.appsflyer.internal.AFb1zSDK.AFInAppEventType(AFb1zSDK.java:77)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at java.lang.Thread.run(Thread.java:784)
```

**Comment by SebPawp** [comment]
Facing the exact same issue on :`6.10.1`

**Comment by pazlavi** [comment]
Hi, @SebPawp, 
Please open a support ticket, as it might be an implementation issue.

**Comment by fernandohbrasilpoq** [comment]
I am facing the same issue on 6.10.1
