### ISSUE TITLE
StrictMode: DiskReadViolation

### ISSUE THREAD

**Issue by auxDK** [AppsFlyerSDK/appsflyer-android-sdk#52]
**Library version:** 6.10.1

Stack trace of the issue
```
StrictMode policy violation; ~duration=124 ms: android.os.strictmode.DiskReadViolation
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
                 	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
                 	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:301)
                 	at com.appsflyer.internal.AFc1ySDK.AFInAppEventParameterName(:23)
                 	at com.appsflyer.internal.AFe1jSDK.AFKeystoreWrapper(:221)
                 	at com.appsflyer.internal.AFe1jSDK.<init>(:44)
                 	at com.appsflyer.internal.AFb1aSDK.afRDLog(:189)
                 	at com.appsflyer.internal.AFb1wSDK.init(:816)
                 	at de.autodoc.analytics.dispatcher.appsflyre.AppsflyerDispatcherImpl.initDispatcher(AppsflyerDispatcherImpl.kt:32)
                 	at my.company.Analytics.init(Analytics.kt:44)
                 	at my.company.Tracker.access$init$s310950758(Tracker.kt:16)
                 	at my.companyTracker$init$1.invokeSuspend(Tracker.kt:35)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7918)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by jsoberg** [comment]
We're still seeing this issue on the latest (16.12.1), and as far back as 16.9.4. This is showing a fairly significant impact (500ms+) to startup times on some occasions - are there plans to address this?
