### ISSUE TITLE
Crash on 6.12.1

### ISSUE THREAD

**Issue by empowerDan** [AppsFlyerSDK/appsflyer-android-sdk#60]
Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFb1mSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFb1mSDK$$>
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFb1mSDK$$.AFKeystoreWrapper(:100)
       at com.appsflyer.internal.AFb1mSDK$$.values(:19)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFb1pSDK.values(:125)
       at com.appsflyer.internal.AFd1eSDK.values(SourceFile:9132)
       at com.appsflyer.internal.AFd1hSDK.values(SourceFile:81)
       at com.appsflyer.internal.AFd1eSDK.AFKeystoreWrapper(SourceFile:78)
       at com.appsflyer.internal.AFd1nSDK.AFInAppEventParameterName(SourceFile:115)
       at com.appsflyer.internal.AFd1tSDK$5.run(SourceFile:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by pazlavi** [comment]
Duplicate #48

**Comment by ge-af** [comment]
Hi, 
We've just released a new Android SDK version that fixes this issue.
The new version is v6.12.2.
