### ISSUE TITLE
java.util.ConcurrentModificationException crash

### ISSUE THREAD

**Issue by fcduarte** [AppsFlyerSDK/appsflyer-android-sdk#63]
Hi folks,

We've been seeing a crash being logged to our Bugsnag:

````
java.util.ConcurrentModificationException
        at android.util.ArrayMap.put(ArrayMap.java:623)
        at android.os.BaseBundle.putLong(BaseBundle.java:842)
        at android.content.Intent.putExtra(Intent.java:10001)
        at com.appsflyer.internal.AFb1sSDK.AFInAppEventParameterName(AFb1sSDK:93)
        at com.appsflyer.internal.AFb1sSDK.valueOf(AFb1sSDK:60)
        at com.appsflyer.internal.AFa1eSDK.values(AFa1eSDK:50261)
        at com.appsflyer.internal.AFa1eSDK.$r8$lambda$iRLOPSnkCxVbqSwnB3mI1vYOzr8(AFa1eSDK:1)
        at androidx.camera.camera2.internal.Camera2CameraControlImpl$$InternalSyntheticLambda$8$5a689fc2a57a5690d75ad6dc926866dea228417000e6e52a5618ff68e715bdc2$0.run$bridge(Camera2CameraControlImpl:1226)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
````

We're running 6.12.2 and unfortunately we can't reproduce it, from the breadcrumbs it looks like the app was just brought to foreground and then crashed.

Thanks!

**Comment by pazlavi** [comment]
Solved in v6.12.3
