### ISSUE TITLE
signal:6 (SIGABRT),code:-1 (SI_QUEUE),fault addr:--------

### ISSUE THREAD

**Issue by LavieMoLLM** [AppsFlyerSDK/appsflyer-android-sdk#67]
Hello, recently there have been dozens of Native Crash related to AppsFlyer in our app, mainly due to thread hang timeout. The thread stack is as follows:

signal:6 (SIGABRT),code:-1 (SI_QUEUE),fault addr:--------
Abort message:
![appsflyer](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/assets/139430561/cc7d6694-5b8b-4480-af36-5b4a107873ce)

Thread suspension timed out: 0x77d96ff888:OkHttp https://dummy.global.com/...
java stacktrace:
at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
at java.lang.Thread.getStackTrace(Thread.java:1841)
at java.lang.Thread.getAllStackTraces(Thread.java:1909)
at com.appsflyer.internal.AFa1xSDK$23740.AFInAppEventType(AFa1xSDK.java:113)
at com.appsflyer.internal.AFa1xSDK$23740.values(AFa1xSDK.java:168)
at com.appsflyer.internal.AFa1xSDK$23740.AFInAppEventParameterName(AFa1xSDK.java:73)
at com.appsflyer.internal.AFa1tSDK$28986.AFKeystoreWrapper(AFa1tSDK.java:38)
at java.lang.reflect.Method.invoke(Method.java)
at com.appsflyer.internal.AFc1oSDK.AFKeystoreWrapper(AFc1oSDK.java:159)
at com.appsflyer.internal.AFd1hSDK.values(AFd1hSDK.java:88)
at com.appsflyer.internal.AFd1oSDK.valueOf(AFd1oSDK.java:144)
at com.appsflyer.internal.AFd1zSDK.afErrorLog(AFd1zSDK.java:207)
at com.appsflyer.internal.AFc1bSDK.run(AFc1bSDK.java:4184)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
![appsflyer](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/assets/139430561/051f67a5-d353-4c5e-86fb-e37f216fb755)

**Comment by LavieMoLLM** [comment]
@pazlavi the email has already sent, plz check the email, feel free to let me know if you still need other information

**Comment by Edison0716** [comment]
Any update for this?

**Comment by BulatInDrive** [comment]
We are also experiencing thousands of native crashes. I managed to catch them on my device. Here are some logs
```
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29531 (queue-1-1), pid 29429 (tartup.myApp)
Cmdline: com.example.myApp
pid: 29429, tid: 29531, name: queue-1-1  >>> com.example.myApp <<<
      #49 pc 000000000048611c  [anon:dalvik-classes34.dex extracted in memory from /data/app/~~hO18nyp771KVUBx-M-n_wg==/com.example.myApp-PIlr__Eh8cgRvuUcZnLvXg==/base.apk!classes34.dex] (com.appsflyer.internal.AFe1rSDK.values+0)
      #54 pc 0000000000489124  [anon:dalvik-classes34.dex extracted in memory from /data/app/~~hO18nyp771KVUBx-M-n_wg==/com.example.myApp-PIlr__Eh8cgRvuUcZnLvXg==/base.apk!classes34.dex] (com.appsflyer.internal.AFf1gSDK.AFKeystoreWrapper+0)
      #59 pc 000000000048d19c  [anon:dalvik-classes34.dex extracted in memory from /data/app/~~hO18nyp771KVUBx-M-n_wg==/com.example.myApp-PIlr__Eh8cgRvuUcZnLvXg==/base.apk!classes34.dex] (com.appsflyer.internal.AFf1qSDK.AFInAppEventParameterName+0)
      #64 pc 000000000048de84  [anon:dalvik-classes34.dex extracted in memory from /data/app/~~hO18nyp771KVUBx-M-n_wg==/com.example.myApp-PIlr__Eh8cgRvuUcZnLvXg==/base.apk!classes34.dex] (com.appsflyer.internal.AFf1xSDK.registerClient+0)
      #69 pc 00000000004833cc  [anon:dalvik-classes34.dex extracted in memory from /data/app/~~hO18nyp771KVUBx-M-n_wg==/com.example.myApp-PIlr__Eh8cgRvuUcZnLvXg==/base.apk!classes34.dex] (com.appsflyer.internal.AFe1aSDK$3.run+0)
```

**Comment by BulatInDrive** [comment]
appsflyer = "6.14.2"
appsflyer-oaid = "6.12.3"

**Comment by Tosuj-work** [comment]
same issue

**Comment by Edison0716** [comment]
> same issue

https://github.com/HuolalaTech/hll-sys-hook-android

@Tosuj-work  you can try this.
