### ISSUE TITLE
v6.15.0 breaks other library resources

### ISSUE THREAD

**Issue by IlyaPechuro** [AppsFlyerSDK/appsflyer-android-sdk#73]
-adaptresourcefilecontents in the proguard-rules specified without a filter changes all files, breaking some of them
For example, the [libphonenumber](https://github.com/google/libphonenumber) metadata, which causes a crash when accessed

**Comment by romaopedro** [comment]
Something similar is happening in our project using version 6.15.1. Seems like some lib was bumped and is causing those errors.
In our case only occurs when running with obfuscation enabled. 

```
isDebuggable = false
isMinifyEnabled = true
isShrinkResources = false
proguardFiles(
...
)

```

The same doesn't happen with version 6.13.0

```
org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton: 'Z6',binds:h21,Z6]'

...

Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton: 'Z6',binds:h21,Z6]'

...

caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton: 'okhttp3.OkHttpClient',binds:okhttp3.OkHttpClient]'

...

Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton: 'okhttp3.Authenticator',binds:okhttp3.Authenticator]'

...

Caused by: kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
at kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream.readTag(Unknown Source:25)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$StringTable.<init>(SourceFile:17)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$StringTable.<init>(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$StringTable$1.parsePartialFrom(SourceFile:2)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$StringTable$1.parsePartialFrom(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream.readMessage(SourceFile:14)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment.<init>(SourceFile:35)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment.<init>(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment$1.parsePartialFrom(SourceFile:2)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment$1.parsePartialFrom(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser.parsePartialFrom(SourceFile:6)
at kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser.parseFrom(SourceFile:4)
at kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser.parseFrom(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment.parseFrom(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.metadata.builtins.ReadPackageFragmentKt.readBuiltinsPackageFragment(Unknown Source:25)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsPackageFragmentImpl$Companion.create(Unknown Source:20)
at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsPackageFragmentProvider.findPackage(Unknown Source:27)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider.fragments$lambda$1(Unknown Source:5)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider.accessor$AbstractDeserializedPackageFragmentProvider$lambda0(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider$$Lambda$0.invoke(Unknown Source:4)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(Unknown Source:97)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider.collectPackageFragments(Unknown Source:12)
at kotlin.reflect.jvm.internal.impl.descriptors.PackageFragmentProviderKt.collectPackageFragmentsOptimizedIfPossible(Unknown Source:21)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.CompositePackageFragmentProvider.collectPackageFragments(Unknown Source:28)
at kotlin.reflect.jvm.internal.impl.descriptors.PackageFragmentProviderKt.collectPackageFragmentsOptimizedIfPossible(Unknown Source:21)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.CompositePackageFragmentProvider.collectPackageFragments(Unknown Source:28)
at kotlin.reflect.jvm.internal.impl.descriptors.PackageFragmentProviderKt.collectPackageFragmentsOptimizedIfPossible(Unknown Source:21) (Ask Gemini)
at kotlin.reflect.jvm.internal.impl.descriptors.PackageFragmentProviderKt.packageFragments(Unknown Source:15)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl.fragments_delegate$lambda$0(Unknown Source:12)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl.accessor$LazyPackageViewDescriptorImpl$lambda0(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl$$Lambda$0.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl.getFragments(Unknown Source:7)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl.memberScope$lambda$3(Unknown Source:9)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl.accessor$LazyPackageViewDescriptorImpl$lambda2(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl$$Lambda$2.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter.lazyScope$lambda$1(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter.accessor$LazyScopeAdapter$lambda0(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter$$Lambda$0.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter.getWorkerScope(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(Unknown Source:10)
at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findClassifierAcrossModuleDependencies(Unknown Source:56)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.computeClassifierDescriptor(Unknown Source:37)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.classifierDescriptors$lambda$0(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.accessor$TypeDeserializer$lambda0(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer$$Lambda$0.invoke(Unknown Source:8)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(Unknown Source:97)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.typeConstructor(Unknown Source:16)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.simpleType(Unknown Source:43)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.type(Unknown Source:65)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassTypeConstructor.computeSupertypes(Unknown Source:57)
at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor.supertypes$lambda$0(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor.accessor$AbstractTypeConstructor$lambda0(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$$Lambda$0.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValueWithPostCompute.invoke(Unknown Source:15) (Ask Gemini)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValueWithPostCompute.invoke(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor.getSupertypes(SourceFile:2)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getNonDeclaredVariableNames(Unknown Source:8)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.variableNames_delegate$lambda$9(Unknown Source:6)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.accessor$DeserializedMemberScope$OptimizedImplementation$lambda4(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$$Lambda$4.invoke(Unknown Source:4)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(SourceFile:1)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.getVariableNames(Unknown Source:7)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.addFunctionsAndPropertiesTo(Unknown Source:34)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(Unknown Source:38)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.allDescriptors$lambda$2(Unknown Source:10)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.accessor$DeserializedClassDescriptor$DeserializedClassMemberScope$lambda1(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$$Lambda$1.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(Unknown Source:0)
at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(Unknown Source:12)
at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(Unknown Source:18)
at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(Unknown Source:17)
at kotlin.reflect.jvm.internal.KClassImpl$Data.declaredNonStaticMembers_delegate$lambda$22(Unknown Source:6)
at kotlin.reflect.jvm.internal.KClassImpl$Data.accessor$KClassImpl$Data$lambda10(Unknown Source:0)
at kotlin.reflect.jvm.internal.KClassImpl$Data$$Lambda$10.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(Unknown Source:17)
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(Unknown Source:0)
at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(Unknown Source:8)
at kotlin.reflect.jvm.internal.KClassImpl$Data.declaredMembers_delegate$lambda$28(Unknown Source:0)
at kotlin.reflect.jvm.internal.KClassImpl$Data.accessor$KClassImpl$Data$lambda16(Unknown Source:0)
at kotlin.reflect.jvm.internal.KClassImpl$Data$$Lambda$16.invoke(Unknown Source:2)
at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(Unknown Source:17) (Ask Gemini)
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(Unknown Source:0)
at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredMembers(Unknown Source:8)
at kotlin.reflect.full.KClasses.getDeclaredFunctions(Unknown Source:17)
at Bm2.a(Unknown Source:81)
at Gr0.invoke(Unknown Source:534)
at org.koin.core.instance.InstanceFactory.create(Unknown Source:57)
... 105 more
```

**Comment by vegeta2102** [comment]
We faced the same problem in 6.15.1. 
It works properly with 6.14.2 !

Any workaround to this  ?

**Comment by extmkv** [comment]
@pazlavi any update on this issue?

**Comment by dmrevis** [comment]
Is this fixed in later versions? Any workarounds?

**Comment by af-fess** [comment]
Hey @dmrevis, we're actively working on this issue. We'll provide an update as soon as we release a fix.

**Comment by tlozovyi-af** [comment]
The root problem of this issue has been identified and we have a fix for it. We are currently in process of verifying and monitoring this solution.
Currently we're targeting to release a new version of AppsFlyer SDK with the fix in 3 weeks from now.

**Comment by pbacher** [comment]
Was 6.16.0 supposed to have a fix for this? Since 6.14 we have not been able to update AppsFlyer sdk because it crashes our release builds with 

`isMinifyEnabled = true
isShrinkResources = true` 

as it ruins our serialization with Retrofit

`Unable to create converter for class kotlin.Result 
...
Caused by: kotlinx.serialization.SerializationException: Serializer for class 'Result' is not found.`

Same happening with the newly released 6.16.0

**Comment by tlozovyi-af** [comment]
AppsFlyer Android SDK v6.16.0 has been released yesterday and it contains a fix for issue -adaptresourcefilecontents flag in proguard rules.

@pbacher As of other issues you mentioned, I'd suggest to contact support, since seems like they are related to the implications of a particular app dependencies/implementation.
