### ISSUE TITLE
Executing in the main thread? ANR reason locked <0x017b2114> 

### ISSUE THREAD

**Issue by AlexeyGodyaev** [AppsFlyerSDK/appsflyer-android-sdk#76]
'com.appsflyer:af-android-sdk:6.15.2'
id 52
name pool-15-thread-1
was active false
errored no
state Runnable
lock reason locked <0x017b2114>
device [itel S663L]
mechanism [AppExitInfo]
os [Android 12]

"main" tid=1 Native
  #00  pc 0x000000000005c0b0  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x000000000014aa73  /apex/com.android.art/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+82)
  #02  pc 0x00000000004d7e5b  /apex/com.android.art/lib/libart.so (art::GoToRunnable(art::Thread*)+298)
  #03  pc 0x00000000004d7d11  /apex/com.android.art/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:335)
  at android.os.Looper.loopOnce (Looper.java:161)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7976)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:553)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
  
"pool-15-thread-1" tid=52 Native
  #00  pc 0x000000000005c0b0  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x000000000014aa73  /apex/com.android.art/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+82)
  #02  pc 0x00000000004d7e5b  /apex/com.android.art/lib/libart.so (art::GoToRunnable(art::Thread*)+298)
  #03  pc 0x00000000004d7d11  /apex/com.android.art/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)
  at com.android.icu.util.regex.MatcherNative.findNextImpl (Native method)
  at com.android.icu.util.regex.MatcherNative.findNext (MatcherNative.java:99)
  at java.util.regex.Matcher.find (Matcher.java:549)
  at java.util.regex.Pattern.split (Pattern.java:1155)
  at java.lang.String.split (String.java:2483)
  at java.lang.String.split (String.java:2525)
  at com.appsflyer.internal.AFa1ySDK.AFAdRevenueData (SourceFile:233)
  at com.appsflyer.internal.AFa1ySDK.AFAdRevenueData (SourceFile:143)
  at com.appsflyer.internal.AFa1ySDK.getMonetizationNetwork (SourceFile:167)
  at com.appsflyer.internal.AFa1ySDK.getRevenue (SourceFile:72)
  at com.appsflyer.internal.AFa1qSDKV270.getRevenue
  at java.lang.reflect.Method.invoke (Native method)
  at com.appsflyer.internal.AFe1qSDK.AFAdRevenueData (SourceFile:169)
  at com.appsflyer.internal.AFf1eSDK.getMediationNetwork (SourceFile:96)
  at com.appsflyer.internal.AFf1oSDK.getCurrencyIso4217Code (SourceFile:118)
  at com.appsflyer.internal.AFe1aSDK$2.run (SourceFile:111)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)

"FrameMetricsAggregator" tid=58 Native
  #00  pc 0x000000000005c0b0  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x000000000014aa73  /apex/com.android.art/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+82)
  #02  pc 0x00000000004d7e5b  /apex/com.android.art/lib/libart.so (art::GoToRunnable(art::Thread*)+298)
  #03  pc 0x00000000004d7d11  /apex/com.android.art/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:335)
  at android.os.Looper.loopOnce (Looper.java:161)
  at android.os.Looper.loop (Looper.java:288)
  at android.os.HandlerThread.run (HandlerThread.java:67)

**Comment by AlexeyGodyaev** [comment]
6.15.2
--
main
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:883)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1393)
	at com.appsflyer.internal.AFd1iSDK.getCurrencyIso4217Code(SourceFile:3)
	at com.appsflyer.internal.AFb1rSDK.init(SourceFile:154)
	at B4.b.g(SourceFile:29)
	at B4.b.f(SourceFile:7)
	at a4.b.c(SourceFile:7)
	at S4.b.f(SourceFile:5)
	at com._._.ClasssApplication.onCreate(SourceFile:64)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6671)
	at android.app.ActivityThread.access$1400(ActivityThread.java:236)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7581)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
