### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/aidl/BaseStub;

### ISSUE THREAD

**Issue by AppCapster** [AppsFlyerSDK/appsflyer-android-sdk#8]
I'm getting this error after migrating to AndroidX.
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/aidl/BaseStub;
        at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:133)
        at com.appsflyer.internal.i.ˏ(:30)
        at com.appsflyer.AppsFlyerLibCore.init(:808)
        at com.monika.Demo.onCreate(Demo.java:77)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by YuFong** [comment]
the same pro

**Comment by alfiewm** [comment]
same, found solution [here](https://stackoverflow.com/questions/59066411/androidx-migration-noclassdeffounderror). 

in short, downgrade installreferrer sdk from 1.1 to 1.0.

**Comment by af-vs** [comment]
Hi!

Indeed there was a known issue in the install referrer library that is supposed to be fixed as of today. Feel free to re-open if this is still relevant for anyone using install referrer 2.0 or above

Thank you!
